service: pizza-to-dynamo
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

functions:
  dynamo:
    handler: handler.create
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:452836010939:event-bus/pizzaria
          pattern:
            source:
              - com.pizza.status
  detail:
    handler: handler.detail
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:452836010939:event-bus/pizzaria
          pattern:
            source:
              - com.pizza.status
            detail-type:
              - Alteracao Pizza
            detail:
              status:
                - pronto
  delivered:
    handler: handler.delivered
    events:
      - sqs:
          arn:
            arn:aws:sqs:us-east-1:452836010939:espera-entrega
          batchSize: 1
          enabled: true